name: Test Formatting

on:
  schedule: 
  - cron: 30 05 15 * *
  workflow_dispatch:


jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Isort Formatting
        run: |
          pip install isort
          isort calculator.py
          git add .
          git commit -m "style: isort cronjob"
          git push --force
            

  
