name: Test Formatting

on:
  schedule: 
  - cron: 30 05 15 * *
  workflow_dispatch:


jobs:
  isort:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Isort Formatting
        run: |
          pip install isort
          isort calculator.py
      - uses: fregante/setup-git-user@v1
      - name: Commit
        run: |
          git commit -m "style: Code Formatting Workflow" -m "Either triggered by cron or workflow_dispatch"
          git push --force
